version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_USER=${ELASTICSEARCH_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - INDEX_NAME=news_2025.04
      - TZ=Asia/Jakarta
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - esnet