version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "8085:8085"
    depends_on:
      - elasticsearch
    networks:
      - esnet